spring:
  application:
    name: Course

  datasource:
    url: jdbc:postgresql://database-2.c3au442sq16u.ap-south-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

server:
  port: 8061

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8079/eureka/
